### ISSUE TITLE
Opt-in for analytics instead of opt-out

### ISSUE THREAD

**Issue by IndianaDschones** [dbbahnhoflive/dbbahnhoflive-android#6]
## Current Implementation

Analytics is enabled until the user manually opts out in the settings. Every user leaves a data trace to analytics providers.

## Suggested Enhancement

Switch from opt-out to explicit opt-in for analytics. Ask the user on the very first app start, if he wants to share data with analytics providers.

DB Streckenagent has a non skippable dialog on the first app start:

![Screenshot_20200822-112630](https://user-images.githubusercontent.com/6652142/90953477-25ccc880-e46c-11ea-893e-0d53239e8f04.png)

Changing analytics state is very convenient. A user can see it on the **top-level settings page:**

![Screenshot_20200822-112701](https://user-images.githubusercontent.com/6652142/90953481-2b2a1300-e46c-11ea-91ed-df156316895e.png)

## Expected Benefits

If a user doesn´t want to share analytics data, his data is **never** shared. The user is always in full control of his (analytics) data.

This _seems_ to be more GDPR compliant (i am not a lawyer).

**Comment by SuVpmoran** [comment]
Dear @IndianaDschones,

Thank you for opening this issue! Actually we already are working on a new way to handle the analytics tracking in the app and we also plan to change the current Opt-Out option to an Opt-In. 

Your example of the DB Streckenagent is really helpful for us as well. 

So thanks again for your input and keep an eye on our following releases, in which this adjustment will be included.

**Comment by SuVpmoran** [comment]
@IndianaDschones, fyi, we changed the Opt-Out to Opt-In for Adobe Analytics in app release 3.12.0.
